version: 2

builds:
  - id: darwin-amd64
    main: ./
    binary: golang-cross
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/macos/amd64
      - PKG_CONFIG_PATH=/sysroot/macos/amd64/usr/local/lib/pkgconfig
      - CC=o64-clang
      - CXX=o64-clang++
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}}
archives:
  - id: golang-cross
    ids:
      - darwin-amd64
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats: [zip]
    wrap_in_directory: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: goreleaser
    name: example-cross
  prerelease: auto
  draft: false
